# install packer: sudo port install packer
# build box for vagrant with https://github.com/nix-community/nixbox
# run: packer build --only=vmware-iso nixos-x86_64.json
# install plugin from https://github.com/nix-community/vagrant-nixos-plugin

Vagrant.configure("2") do |config|
  config.vm.synced_folder "~/code", "/mnt/code"
  config.vm.synced_folder "~/Pictures", "/mnt/pictures"
  config.vm.synced_folder "~/Downloads", "/mnt/downloads"
  config.vm.synced_folder "~/Documents", "/mnt/documents"
  config.vm.define "nixos2009" do |nixos2009|
      nixos2009.vm.box = "griff/nixos-stable-x86_64"
      nixos2009.vm.hostname = "nixos2009"
      config.vm.provider :vmware_desktop do |v|
          v.gui = false
          v.memory = 1024
          v.cpus = 1
          v.vmx["ethernet0.pcislotnumber"] = "33"
      end
  end
end
