Vagrant.configure("2") do |config|
    config.vm.synced_folder "~/code", "/mnt/code"
    config.vm.synced_folder "~/Pictures", "/mnt/pictures"
    config.vm.synced_folder "~/Downloads", "/mnt/downloads"
    config.vm.synced_folder "~/Documents", "/mnt/documents"
    config.vm.define "virtualbox" do |archlinux|
        archlinux.vm.box = "archlinux/archlinux"
        archlinux.vm.hostname = "iusearchbtw"
        archlinux.vm.network :private_network, ip: "172.16.3.7"

        config.vm.provider :virtualbox do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
end
