# TODO: Update to use vmware fusion provider, needs a custom box build

Vagrant.configure("2") do |config|
    config.vm.synced_folder "~/code", "/mnt/code"
    config.vm.synced_folder "~/Pictures", "/mnt/pictures"
    config.vm.synced_folder "~/Downloads", "/mnt/downloads"
    config.vm.synced_folder "~/Documents", "/mnt/documents"
    config.vm.define "archlinux" do |archlinux|
        archlinux.vm.box = "generic/arch"
        archlinux.vm.hostname = "iusearchbtw"

        config.vm.provider :vmware_desktop do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
end
