Vagrant.configure("2") do |config|
    config.vm.synced_folder "~/code", "/mnt/code"
    config.vm.synced_folder "~/Pictures", "/mnt/pictures"
    config.vm.synced_folder "~/Downloads", "/mnt/downloads"
    config.vm.synced_folder "~/Documents", "/mnt/documents"
    config.vm.define "ubuntu2010" do |ubuntu2010|
        ubuntu2010.vm.box = "bento/ubuntu-20.10"
        ubuntu2010.vm.hostname = "ubuntu2010"

        config.vm.provider :vmware_desktop do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
end
