# build box for vagrant with https://github.com/nix-community/nixbox
# install plugin from https://github.com/nix-community/vagrant-nixos-plugin

Vagrant.configure("2") do |config|
  config.vm.synced_folder "~/code", "/mnt/code"
  config.vm.synced_folder "~/Pictures", "/mnt/pictures"
  config.vm.synced_folder "~/Downloads", "/mnt/downloads"
  config.vm.define "virtualbox" do |nixos2003|
      nixos2003.vm.box = "nixos-20.09-virtualbox-x86_64.box"
      nixos2003.vm.hostname = "nixos-20-09"
      nixos2003.vm.network :private_network, ip: "172.16.3.5"
      config.vm.provider :virtualbox do |v|
          v.gui = false
          v.memory = 1024
          v.cpus = 1
      end
  end
  config.vm.provision :nixos,
    run: 'always',
    expression: {
      environment: {
        systemPackages: [ :htop ]
      }
    }
end
