Vagrant.configure("2") do |config|
    config.vm.synced_folder "~/code", "/mnt/code"
    config.vm.synced_folder "~/Pictures", "/mnt/pictures"
    config.vm.synced_folder "~/Downloads", "/mnt/downloads"
    config.vm.synced_folder "~/Documents", "/mnt/documents"
    config.vm.define "ubuntu1804" do |ubuntu1804|
        ubuntu1804.vm.box = "hashicorp/bionic64"
        ubuntu1804.vm.hostname = "ubuntu1804"

        config.vm.provider :vmware_desktop do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
end
