Vagrant.configure("2") do |config|
    config.vm.synced_folder "~/code", "/mnt/code"
    config.vm.synced_folder "~/Pictures", "/mnt/pictures"
    config.vm.synced_folder "~/Downloads", "/mnt/downloads"
    config.vm.define "virtualbox" do |ubuntu2004|
        ubuntu2004.vm.box = "bento/ubuntu-20.04"
        ubuntu2004.vm.hostname = "ubuntu-20-04"
        ubuntu2004.vm.network :private_network, ip: "172.16.3.3"

        config.vm.provider :virtualbox do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
end
