Vagrant.configure("2") do |config|
    config.vm.synced_folder "~/code", "/mnt/code"
    config.vm.synced_folder "~/Pictures", "/mnt/pictures"
    config.vm.synced_folder "~/Downloads", "/mnt/downloads"
    config.vm.synced_folder "~/Documents", "/mnt/documents"
    config.vm.define "virtualbox" do |ubuntu1804|
        ubuntu1804.vm.box = "geerlingguy/ubuntu1804"
        ubuntu1804.vm.hostname = "ubuntu-18_04"
        ubuntu1804.vm.network :private_network, ip: "172.16.3.2"

        config.vm.provider :virtualbox do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end
end
